// Build the Weldrite design system: one ESM bundle for the converter to wrap
// into window.WeldriteDS, plus emitted .d.ts declarations for prop extraction.
// CSS is intentionally NOT bundled into the JS — design-sync ships styles.css
// and tokens.css as standalone stylesheets (cfg.cssEntry / cfg.tokensGlob).
import { build } from 'esbuild';
import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

rmSync('dist', { recursive: true, force: true });
mkdirSync('dist', { recursive: true });

// Ship ONE stylesheet that carries both the tokens and the component rules, so
// design-sync's single cssEntry puts everything in the design closure (its
// token copier only pulls from installed packages, which a self-repo DS lacks).
const css =
  '/* Weldrite design system — tokens + components (generated by build.mjs) */\n' +
  readFileSync('src/tokens.css', 'utf8') +
  '\n' +
  readFileSync('src/styles.css', 'utf8');
writeFileSync('dist/weldrite.css', css);

await build({
  entryPoints: ['src/index.ts'],
  outfile: 'dist/index.es.js',
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2019',
  jsx: 'automatic',
  // React is provided by the host (the design agent's runtime vendors it).
  external: ['react', 'react-dom', 'react/jsx-runtime'],
  logLevel: 'info',
});

// Declaration files give design-sync the <Name>Props contracts.
execSync('npx tsc -p tsconfig.json', { stdio: 'inherit' });
console.log('weldrite design-system build complete');
